# Generated by Django 4.2.21 on 2025-05-23 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_csv_user"),
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="csv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="files.csv"
            ),
        ),
    ]
